# Generated by Django 5.1 on 2024-08-25 12:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="subid",
        ),
    ]
