# Generated by Django 5.1 on 2024-08-26 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionpaper",
            name="module",
        ),
    ]
