# Generated by Django 5.1 on 2024-08-25 13:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_remove_department_subid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="depsubrel",
            name="name",
        ),
    ]
