# Generated by Django 5.1 on 2024-08-30 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_remove_questionpaper_module"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="democlass",
            name="link",
        ),
        migrations.RemoveField(
            model_name="democlass",
            name="name",
        ),
    ]
