# Generated by Django 5.1 on 2024-08-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_remove_democlass_link_remove_democlass_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="democlass",
            name="courselink",
            field=models.URLField(default=""),
        ),
        migrations.AddField(
            model_name="democlass",
            name="demolink",
            field=models.URLField(default=""),
        ),
    ]
