# Generated by Django 5.1 on 2024-08-30 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_democlass_courselink_democlass_demolink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gate",
            name="depid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.department"
            ),
        ),
    ]
