# Generated by Django 5.1 on 2024-08-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_alter_gate_depid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gate",
            name="reg_file_id",
        ),
        migrations.AddField(
            model_name="gate",
            name="reg_file_link",
            field=models.URLField(default=""),
        ),
    ]
