# Generated by Django 5.1 on 2024-08-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_remove_gate_reg_file_id_gate_reg_file_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bundle",
            name="reg_file_id",
        ),
        migrations.AddField(
            model_name="bundle",
            name="reg_file_link",
            field=models.URLField(default=""),
        ),
    ]
