# Generated by Django 5.1 on 2024-08-30 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_remove_bundle_reg_file_id_bundle_reg_file_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bundle",
            name="depid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.department"
            ),
        ),
    ]
