# Generated by Django 5.1 on 2024-08-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_alter_bundle_depid"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="courselink",
            field=models.URLField(default=""),
        ),
        migrations.AddField(
            model_name="subject",
            name="demolink",
            field=models.URLField(default=""),
        ),
        migrations.DeleteModel(
            name="DemoClass",
        ),
    ]
