# Generated by Django 5.1 on 2024-08-30 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_subject_courselink_subject_demolink_delete_democlass"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GateDEP",
        ),
        migrations.AlterField(
            model_name="project",
            name="depid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.department"
            ),
        ),
        migrations.AlterField(
            model_name="internship",
            name="depid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.department"
            ),
        ),
        migrations.DeleteModel(
            name="InternDep",
        ),
    ]
