# Generated by Django 5.1 on 2024-08-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_delete_gatedep_alter_project_depid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="files",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
