# Generated by Django 5.1 on 2024-09-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0011_alter_notification_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="fileblob",
            field=models.FileField(default=1, upload_to="uploads/"),
            preserve_default=False,
        ),
    ]
