# Generated by Django 5.1 on 2024-09-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0012_file_fileblob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="fileblob",
            field=models.BinaryField(),
        ),
    ]
