# Generated by Django 5.1 on 2024-09-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0013_alter_file_fileblob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="fileblob",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
